version: "3.8"

services:
  app:
    command: >
      sh -c "python3 manage.py migrate &&
             python3 manage.py runserver 0.0.0.0:8000"
    image: alexeynaidiuk/django-store:latest
    restart: always
    environment:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./static:./static
  db:
    image: postgres:15-alpine
    restart: always
    env_file:
      - .env
    ports:
      - "5431:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - '6378:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - ./redis:/data
    depends_on:
      - db
