# Generated by Django 3.2.15 on 2023-08-30 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='bucket_history',
            field=models.JSONField(default=dict),
        ),
    ]
