# Generated by Django 3.2.15 on 2023-08-28 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_bucket'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
