# Generated by Django 3.2.15 on 2023-08-31 12:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('products', '0004_auto_20230828_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stripe_price',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
